### ISSUE TITLE
Serving `*.js` files as static assets

### ISSUE THREAD

**Issue by kersh** [flawyte/now-basic-auth#1] opened 2019-03-24 22:19 UTC
Hi Mickaël,
Thank you very much for you work and making this repo with basic-auth examples! I found these examples pretty useful!

### Issue
I've tested things locally with my own repo and compared it to your examples and noticed that `_static` directory doesn't contain any `*.js` files and there are no `<script src="*.js"></script>` lines in the `_static/index.html`.
It seems that express serves all `*.css` and `.svg` files however fails on `*.js` (and maybe on some other extension, I didn't test it that far)

### Reproduce steps
1. Create  an empty `main.js` within `_static/`.
2. Add `<script src="main.js"></script>` line in `_static/index.html`.
3. Deploy via now.
All `*.js` files will fail with 404:
![image](https://user-images.githubusercontent.com/621330/54886612-9136f300-4e92-11e9-874a-f8ce798d1ff8.png)
_(note that `styles.css` loaded just fine)_

### What I've tried
- I've checked all the paths many times to make sure they are correct.
- I've tried to add a second `build` with `@now/static`.
- I've played with the `router` in `now.json`.

Nothing helped me but I'm new to `now` so I think I'm missing something.

### Conclusion
I would appreciate if you could find time and try to update your examples with `*.js` files added. I also would be really thankful if you could give me a hint to point me in the right direction in my investigation of this problem.

Have a nice day! 👍

**Comment by flawyte** [comment] 2019-03-26 20:55
Hi Vladimir,
Thanks a lot for taking the time to write such a clear and detailed issue ! 👏

I'll take a look asap and (hopefully) come back to you with a solution, as I'll soon need to load JS files in one of my projects too.

I'll keep you updated 😉

**Comment by flawyte** [comment] 2019-04-08 18:38
I tried to reproduce and got the same results : a 404 for every JS file I try to serve.

I think it's a problem with either the `now.json` file or how Now handles JS files that aren't built by any builder. I've posted a [message](https://spectrum.chat/zeit/now/cant-serve-js-files-through-node~27e5b248-5b1e-4a33-8303-0a5aa279c979) on their chat.

**Comment by flawyte** [comment] 2019-04-11 16:34
It looks like it's a [problem](https://github.com/zeit/now-builders/issues/381) with the Now platform and `fs` not being able to read `.js` files.

In the future we might be able to use the `config.includeFiles` property to indicate that we want the JS files to be bundled with the lamba, but it's not working for me at the moment ([issue1](https://github.com/zeit/now-builders/issues/377), [issue2](https://github.com/zeit/now-builders/issues/381)).

In the meantime, the solution is to let `@now/static` build your JS files and add a route to let Now serve them (instead of doing it through Node) :

```diff
{
  "builds": [
    {
      "src": "index.js",
      "use": "@now/node"
-   }
+   },
+   {
+     "src": "**/*.js",
+     "use": "@now/static"
+   }
  ],
  "routes": [
+   {
+     "src": "/(.*).js",
+     "dest": "/$1.js"
+   },
    {
      "src": "/.*",
      "dest": "index.js"
    }
  ]
}
```

It means that they **won't** be protected by auth, and anyone who knows the exact URL of any `.js` file will be able to access it. *But*, given that these files are loaded from HTML, unauthorized users that won't see your HTML pages won't even know your JS files exist either.

**Comment by kersh** [comment] 2019-04-12 06:47
Thank you a lot, Mickaël! Great investigation of the issue!
Looks like this issue might be useful to link in the README within "Known Issues" section, this could be something like that:
```md
## Known Issues

[Serving `*.js` files is not working properly](https://github.com/flawyte/now-basic-auth/issues/1#issuecomment-482189475)
```

**Comment by flawyte** [comment] 2019-04-12 10:18
Yep! Great idea!
Closing this issue for now. Feel free to re-open if the workaround doesn't work for you :)

**Closed by flawyte** 2019-04-12 10:18 UTC

**Comment by flawyte** [comment] 2019-05-20 17:42
For the record, `config.includeFiles` now works as expected and examples have been updated to use it (see [this commit](https://github.com/flawyte/now-basic-auth/commit/9a944f835b011d79766a9a5d6d9272301cff0fc3)).

This means that **`.js` files can now be protected by basic auth too**, and you don't need the [above-mentioned workaround](https://github.com/flawyte/now-basic-auth/issues/1#issuecomment-482189475) anymore.
